# Generated by Django 5.2 on 2025-04-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
