# Generated by Django 5.2 on 2025-04-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
