# Generated by Django 5.2 on 2025-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_restaurant_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
