# Generated by Django 5.2 on 2025-04-14 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__range', (1, 5))), name='rating_valid_value', violation_error_message='Invalid rating, It must be between 1 and 5'),
        ),
    ]
