# Generated by Django 5.2 on 2025-04-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rating_rating_valid_value'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='valid_latitude', violation_error_message='Latitude must be between -90 and 90'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='valid_longitude', violation_error_message='Latitude must be between -180 and 180'),
        ),
    ]
