# Generated by Django 5.2 on 2025-04-14 14:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_restaurant_valid_latitude_restaurant_valid_longitude'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='restaurant_name_unique_insensitive'),
        ),
    ]
