# Generated by Django 5.2 on 2025-04-15 14:49

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_restaurant_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='profit',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('income'), '-', models.F('expenditure')), output_field=models.DecimalField(decimal_places=2, max_digits=8)),
        ),
    ]
