# Generated by Django 5.2 on 2025-04-15 15:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sale_suggested_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('duration', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('end_date'), '-', models.F('start_date')), output_field=models.DurationField())),
            ],
        ),
    ]
